version: 2

project_name: terraform-provider-airtelcloud

dist: dist

before:
  hooks:
    - go mod tidy

builds:
  - id: terraform-provider

    binary: terraform-provider-airtelcloud

    env:
      - CGO_ENABLED=0

    ldflags:
      - -s -w

    goos:
      - darwin
      - linux
      - freebsd
      - openbsd
      - solaris
      - windows

    goarch:
      - amd64
      - arm64
      - arm
      - "386"

    ignore:
      # Darwin
      - goos: darwin
        goarch: arm

      - goos: darwin
        goarch: "386"

      # Solaris
      - goos: solaris
        goarch: arm64

      - goos: solaris
        goarch: arm

      - goos: solaris
        goarch: "386"

      # OpenBSD
      - goos: openbsd
        goarch: arm

      - goos: openbsd
        goarch: arm64

      # Linux
      - goos: linux
        goarch: arm64

      # FreeBSD
      - goos: freebsd
        goarch: arm64

      # Windows
      - goos: windows
        goarch: arm

      - goos: windows
        goarch: arm64

archives:
  - id: provider

    formats:
      - zip

    name_template: >-
      {{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

signs:
  - id: checksum
    artifacts: checksum
    signature: "${artifact}.sig"

snapshot:
  version_template: "{{ incpatch .Version }}-dev"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: Airtel-Cloud-Platform
    name: terraform-provider-airtelcloud

  draft: false
  prerelease: auto
  replace_existing_draft: true

source:
  enabled: true
